env: CI=true
language: node_js
node_js:
  - "0.12.7"
branches:
  only:
    - master
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g bower grunt-cli karma
  - npm install
  - bower install
script:
  - grunt test
notifications:
  email:
    - quentin.lampin@gmail.com
